language: erlang
otp_release:
  - 19.0
  - 18.2.1
  - 18.1
  - 18.0
  - 17.5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - golang
      - ninja-build
env:
  - CXX=g++-4.9 CC=gcc-4.9
before_install:
  - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.sh
  - sudo sh cmake-3.5.2-Linux-x86_64.sh --prefix=/usr --exclude-subdir
